services:
  compose-secret-svr:
    image: alpine:3.20
    container_name: compose-secret
    restart: unless-stopped
    # Монтируем секрет в контейнер
    secrets:
      - my_compose_secret
    # Основные параметры запуска
    command: ["sh", "-c", "sleep 3600"]

# Объявляем секреты
secrets:
  my_compose_secret:
    environment: MY_COMPOSE_SECRET

